namespace TNet.Server;

internal enum RoomCMD
{
	none = 0,
	drag_list = 1,
	drag_list_res = 2,
    create = 3,
    create_res = 4,
    destroy = 5,
	destroy_res = 6,
    destroy_notify = 7,
    join = 8,
    join_res = 9,
    join_notify = 10,
    leave = 11,
    leave_notify = 12,
    kick_user = 13,
	kick_user_notify = 14,
	rename = 15,
	rename_notify = 16,
	set_var = 17,
    var_notify = 18,
    set_user_var = 19,
    user_var_notify = 20,
    set_user_status = 21,
    user_status_notify = 22,
	send_msg = 23,
	broadcast_msg = 24,
    msg_notify = 25,
    lock_req = 26,
    lock_res = 27,
    unlock_req = 28,
	unlock_res = 29,
	start = 30,
    start_notify = 31,
    creater_notify = 32,
    set_create_param = 33,
	create_param_change = 34
}