# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: Triniti
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore T/T.csproj
    - name: Build
      run: dotnet build --no-restore T/T.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run
      run: |
        dotnet T/BuildOutput/T.dll &
        APP_PID=$!
        echo "App started with PID $APP_PID"
        sleep 10
        if ps -p $APP_PID > /dev/null; then
          echo "App is running!"
        else
          echo "App crashed!"
          exit 1
        fi
        kill $APP_PID

